### ISSUE TITLE
macro error

### ISSUE THREAD

**Issue by frederiquejasmine1990** [pmascalchi/ImageJ-macros#2]
Hi, I'm trying to adjust the white balance through this macro but I get stuck at trying to run it. Anyone familiar with this problem?

<img width="610" alt="Schermafbeelding 2022-12-06 om 11 37 17" src="https://user-images.githubusercontent.com/119935619/205889317-c30f646a-947f-49c7-97df-862e9718d0a9.png">

**Comment by pmascalchi** [comment]
Hi @frederiquejasmine1990 , the HTML code that you see (with "<") means you didn't download the macro, but rather downloaded the web page. I know it's confusing in GitHub.
Please right-click on the "Raw" button [on this page](https://github.com/pmascalchi/ImageJ_Auto-white-balance-correction/blob/master/White%20balance%20correction_1.0.ijm), and select "Save link as":

![image](https://user-images.githubusercontent.com/18047969/205908907-0f5131c1-c51a-4d2a-9b59-894b5410e899.png)
